version: "3.9"

services:
  sa_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    # volumes:
    #   - ./source/public/custom-logo:/usr/share/nginx/html/custom-logo:ro
    networks:
      - sa_shared
      - default
    restart: always

networks:
  default:
  sa_shared:
    external: true